"""added source url

Revision ID: 6fe54f0d066e
Revises: 6d002c7f35d1
Create Date: 2025-09-04 16:55:30.796577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe54f0d066e'
down_revision: Union[str, Sequence[str], None] = '6d002c7f35d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('source', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'source')
    # ### end Alembic commands ###
